### ISSUE TITLE
Add end to end test for the TokenBridge and Messaging

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#122]
## Description
Add end to end test for the TokenBridge and Messaging that includes bridging tokens from L1 to L2 and L2 to L1.

## Motivation
Additional confidence that interaction behaves as expected.

## Tasks
- [x] Add Deployments for the TokenBridge on L1 in the local stack
- [x] Add Deployments for the TokenBridge on L2 in the local stack
- [ ] Create and add a deploy for an ERC20 in the local stack for testing
- [ ] Add end to end test for L1 to L2 token sending (use manual claiming on L2)
- [ ] Add end to end test for L2 to L1 token sending (use manual claiming on L1)

## Acceptance criteria
- [ ] Tokens can be bridged in either direction through the local stack
- [ ] Leverages the existing end to end test framework (additive not replacement)

## Risks
- [ ] Slower pipeline - expected, but noted for completeness and to indicate that consideration should be paid toward time.
- [ ] More complexity to the local stack
