### ISSUE TITLE
Split out pause manager types for cleaner code breakdown

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#124]
## Description
Split out pause manager types for cleaner code breakdown.

## Motivation
Upon reevaluation, it made more sense from a code size, and code cleanliness perspective to split out the particular pause roles and types for the LineaRollup, L2MessageService and the TokenBridge.

Previously it was designed to not have multiple versions for each contract to simplify management, but the granularity dictates the need to split it out.

## Tasks
- [ ] Separate the inherited PauseManager to be specific for each of the specified contracts

## Acceptance criteria
- [ ] LineaRollup does not contain any L2MessageService or TokenBridge types or roles
- [ ] L2MessageService does not contain any LineaRollup or TokenBridge types or roles
- [ ] TokenBridge does not contain any L2MessageService or LineaRollup types or roles

## Risks
- [ ] Overlaps of types could cause confusion, but it is cleaner and specific to each deploy
