### ISSUE TITLE
Review Beta v2 contract changes and update coordinator

### ISSUE THREAD

**Issue by julien-marchand** [Consensys/linea-monorepo#127]
## Description
Review Beta v2 contract changes and update coordinator

## Tasks
- [ ] Review the list of PRs part of Beta v2
- [ ] List impacts on the coordinator
- [ ] Update the coordinator
