### ISSUE TITLE
Improve the tx history in the Bridge UI

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#128]
## Description
The transaction history in the Bridge UI is not updating correctly sometime and it's taking quite some time. We need to ensure accurate and timely updates without further degrading performance.

## Motivation
Improving the transaction history will provide users with a better experience.

## Tasks
- [ ] Identify performance bottlenecks related to transaction history loading and updates
- [ ] Implement efficient solutions to load the transaction history
- [ ] Optimize performance to minimize UI slowdowns

## Acceptance criteria
- [ ] Transaction history loads promptly and accurately
- [ ] Performance is improved
- [ ] No major slowdowns in the UI after the fix

## Risks
- [ ] Further performance issues if not optimized properly
- [ ] Risk of incomplete or delayed transaction history updates

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
