### ISSUE TITLE
Enable auto-deposits for ERC-20 to L2 (deposits only) in the Postman

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#130]
## Description
Configure Postman to support auto-deposits for ERC-20 tokens from L1 to L2.

## Motivation
Setting up auto-deposits in Postman will allow users to automatically deposit ERC20 tokens.

## Tasks
- [ ] Configure Postman for ERC-20 auto-deposits
- [ ] Ensure only deposits are automated (no withdrawals)
- [ ] Test the configuration to ensure correct behavior

## Acceptance criteria
- [ ] Postman is correctly configured to handle ERC-20 auto-deposits to L2
- [ ] Deposits can be automated using the Postman setup
- [ ] The configuration is tested and works as expected
