### ISSUE TITLE
State Recovery - Decompress & Recover block data from blobs

### ISSUE THREAD

**Issue by jpnovais** [Consensys/linea-monorepo#132]
## Description
Decompress and Recover block data from compressed Blobs published on L1. 

## Motivation
Necessary for state recovery

## Tasks
- [ ] Use decompressor to decompress the data as rebuild block data

## Acceptance criteria
- [ ] Test: Decompress and Recover block data to domain model.
- [ ] Test: Given a Linea block interval, compress the blocks, decompress the blocks, and recover them to the Domain Model.
  - [ ] This can be a manual integration tool and does not need to be part of CI.

## Notes:
Domain model is created in [here](https://github.com/Consensys/linea-monorepo/blob/state-reconstruction-app/state-recover/app-core/src/main/kotlin/net/consensys/linea/staterecover/domain/DomainModels.kt)
