### ISSUE TITLE
Reduce size of docker images - Remove unnecessary dependencies 

### ISSUE THREAD

**Issue by bradbown** [Consensys/linea-monorepo#134]
## Description
There will be un-required transitive dependencies in our docker images which can be excluded to reduce the size of our various docker images.

## Motivation
Reduces size of docker images.

## Tasks
- [ ] Investigate transitive dependencies which can be removed.

## Acceptance criteria
- [ ] All tests still pass after exclusions.

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.

**Comment by jonesho** [comment]
https://github.com/Consensys/linea-monorepo/pull/118
