### ISSUE TITLE
Refactor CI to push Docker images  from main

### ISSUE THREAD

**Issue by julien-marchand** [Consensys/linea-monorepo#181]
## Description
Refactor CI to push Docker images from main

## Motivation
Have more transparency on where images have been built. Ensure all deployed software has been built from main. Streamline the release process. Ensure no docker image is pushed from branches and forks.

## Tasks
- [ ] Reuse locally built images when running e2e tests
- [ ] Don't push docker images on branches/PR
- [ ] Push images at the end of the workflow on main

## Risks
- [ ] Make it harder to debug failures in e2e related to runners/CI
