### ISSUE TITLE
JVM client for Linea Smart Contract V6

### ISSUE THREAD

**Issue by jpnovais** [Consensys/linea-monorepo#189]
## Description
Build and publish mvn jar for Linea Rollup smart contract V6. New Class shall be called `LineaRollupV6` 

## Tasks
- [ ] Issue a mvn package of `jvm-libs/linea-contracts/l1-rollup`. Version shall be `6.0.0`, however, it's recommended to release first with `6.0.0-rc1` until we have 100% integration test;
- [ ] Potentially adapt release jobs to support optional package classifier "build.linea:l1-rollup-contract-client:6.0.0:**rc1**"

## Acceptance criteria
- [ ] Package is issued in mvn repository.

**Comment by thedarkjester** [comment]
@jpnovais give we are using the SemVer 2.0 with M.m versioning, would this not be 
`build.linea:l1-rollup-contract-client:6.0:rc1`

**Comment by jpnovais** [comment]
What if there is a but and you want to patch?
IMO, it should be 6.0.0:**rc1**, the RC1 means that it's still a work in progress and it not stable.

**Comment by thedarkjester** [comment]
Am I correct then in saying this does not align directly with the smart contract version itself, but just the client then?

**Comment by jpnovais** [comment]
Image that you release the official `V6.0` (not the RC1);  then you realise that there is a bug on the JAVA web3j generated wrapper, you patch it, what should the next version of that patch be?
