### ISSUE TITLE
Improve open source documentation for smart contracts and its tests

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#191]
## Description
Improve open source documentation for smart contracts that covers Styling, Linting, Folder structure, and naming conventions for both the smart contracts and its tests.

## Motivation
This will make it easier for external contributors to submit pull requests and for the team to validate the PRs in a consistent manner.

## Tasks
- [ ] Add documentation for Smart Contracts
- [ ] Add documentation for Smart Contract Testing

## Acceptance criteria
- [ ] Documentation is clear and easy to understand

## Risks
- [ ] These are risks that may prevent completion of the task as well as areas to pay special attention to
