### ISSUE TITLE
Update to Kotlin 2.X

### ISSUE THREAD

**Issue by jpnovais** [Consensys/linea-monorepo#203]
## Description
Update to Kotlin 2.0. 

The scope is to update the language version in [gradle configs ](https://github.com/Consensys/linea-monorepo/blob/main/buildSrc/build.gradle#L11) and fix any eventual compiler breaking changes to allow team/project to benefit for new version as soon as possible.

## Motivation
- benefit from Koltin 2x new features. Release [notes](https://kotlinlang.org/docs/whatsnew20.html)
- more performant compile 
- Avoid writing new code in outdated version

## Tasks
- [ ] Update Koltin compiler/versions in gradle configs
- [ ] Fix eventual breaking changes 

## Acceptance criteria
- [ ] Green end2end build
- [ ] Compile new version of Besu plugins and test integration

**Comment by julien-marchand** [comment]
Could be addressed with #981 #979
