### ISSUE TITLE
Add support for Foundry compilation and basic testing

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#268]
## Description
Add support for Foundry compilation and basic testing

## Motivation
In order to support the community, auditors and prospective bug bounty hunters, adding Foundry support for the contracts and testing will be useful.

## Tasks
- [x] Add config and fixed version dependent packages
- [x] Add simple test and compilation to validate bytecode

## Acceptance criteria
- [x] Hardhat testing, deploy and compilation works
- [ ] Foundry compilation and config yields the same bytecode
- [x] Foundry testing coverage, gas reporting and fuzzing can be increased as time goes on
- [ ] Setup and install process is documented
