### ISSUE TITLE
Chore: Remove unused and older contracts, deployment scripts and tests

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#269]
## Description
Chore: Remove unused and older contracts, deployment scripts, and tests in the repository. e.g. `LineaRollupInit`

## Motivation
A cleaner codebase, less confusion for auditors and bug bounty hunters and makes future audit scoping easier.

## Tasks
- [ ] Remove contracts and tests that are no longer applicable to the current or next version contracts

## Acceptance criteria
- [ ] All code still compiles and tests pass
- [ ] Code coverage is unchanged or improved
- [ ] Codebase is easier to understand

## Risks
- [ ] Accidentally delete tests covering certain parts of the codebase
