### ISSUE TITLE
Refactor the operational npm packages

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#30]
## Description
Refactor the `operations` folder to improve its structure, organization, and maintainability. This involves organizing code by feature, separating configuration and scripts, cleaning up ignored files, and modularizing the code.

## Motivation
The current structure of the `operations` folder is not optimal for maintainability. By refactoring the folder, we can make the codebase more navigable, easier to manage, and more maintainable in the long run.

## Tasks
- [x] Organize code by feature, grouping related files together.
- [x] Use consistent naming conventions for files and directories.
- [x] Separate configuration files from source code.
- [x] Clean up `.gitignore`, `.dockerignore`, and other ignore files.
- [x] Modularize large files into smaller, more manageable modules.
- [x] Update `package.json` scripts to reflect the new paths.
- [x] Update `tsconfig.json` and `tsconfig.build.json` to include the new paths.
- [x] Ensure Dockerfiles are updated to reflect the new structure.

Here is an example of structure that can be used:
```
operations/
├── src/
│   ├── common/                # Common utilities and helpers
│   │   ├── __tests__/         # Unit tests for common utilities
│   │   ├── utils/             # Utility functions
│   │   │   ├── config.ts      # Configuration-related utilities
│   │   │   └── helpers.ts     # General helper functions
│   ├── synctx/                # Synchronization tasks
│   │   ├── bin/               # Executable scripts
│   │   │   ├── dev.js        
│   │   │   ├── dev.cmd       
│   │   │   └── run.js       
│   │   ├── src/               
│   │   │   ├── index.ts       # Main entry point for synctx
│   │   │   └── utils.ts       # Utility functions for synctx
│   ├── ethTransfer/           # Ethereum transfer tasks
│   │   ├── index.ts           # Main entry point for ethTransfer
│   │   └── utils.ts           # Utility functions for ethTransfer
│   ├── Dockerfile             
│   ├── Dockerfile.alpine      
│   ├── package.json          
│   ├── tsconfig.json        
│   ├── tsconfig.build.json   
│   ├── .eslintignore          
│   ├── .prettierignore     
│   ├── .prettierrc.js         

```
## Acceptance criteria
- [ ] Code is organized by feature, with related files grouped together.
- [ ] Consistent naming conventions are used throughout the `operations` folder.
- [ ] Configuration files are separated from source code.
- [ ] Ignore files are properly configured and cleaned up.
- [ ] Large files are broken down into smaller, more manageable modules.
- [ ] `package.json` scripts are updated and functional.
- [ ] TypeScript configuration files (`tsconfig.json` and `tsconfig.build.json`) are updated and functional.
- [ ] Dockerfiles are updated and functional.

## Risks
- [ ] Potential for breaking changes if paths are not updated correctly.
- [ ] Risk of missing dependencies or configurations during the refactor.
- [ ] Ensure all scripts and configurations are thoroughly tested after refactoring.

## Remember to
- [ ] Add the `documentation` label in case there is an impact on the documentation.
- [ ] Add `priority` and `team` labels.
- [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
