### ISSUE TITLE
Fix CI issue when testing workflow is skipped because of no changes

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#328]
## Description
The CI pipeline skips tests when no code changes are detected in `coordinator`, `prover`, `postman`, `traces-api-facade` and `transaction-exclusion-api`. 

## Motivation
Update the workflow to ensure that the `testing` workflow is always considered successful even if no tests are run.

## Tasks
- [ ] Update CI configuration to always run tests.

## Acceptance criteria
- [ ] Tests run regardless of detected changes.

## Risks
- [ ] Misconfiguration causing unnecessary test runs.

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
