### ISSUE TITLE
Deploy and configure LSC Operational Safe

### ISSUE THREAD

**Issue by julien-marchand** [Consensys/linea-monorepo#343]
## Description
Deploy and configure LSC Operational Safe and delegate roles to this Safe.

## Motivation
Make it easier to configure the LSC Main Safe.

## Tasks
- [ ] Deploy new Safe
- [ ] Document roles to delegate
- [ ] Delegate OZ roles
- [ ] Add to monitoring tools
- [ ] Increase `minDelay` to 1m on Sepolia, 1d on Mainnet
