### ISSUE TITLE
Publish jvm libs as separate importable jars

### ISSUE THREAD

**Issue by Filter94** [Consensys/linea-monorepo#344]
## Description
In order to reuse utilities we have in jvm-libs, we need to publish them individually

## Motivation
This will improve reusability of the utilities we've built in linea-monorepo

## Tasks
- [ ] Define how package identifiers are going to look like
- [ ] Implement publishing logic from main

## Acceptance criteria
- [ ] jvm-libs packages are published and publically available 

## Risks
- [ ] We shouldn't allow publishing from forks to Linea jar repo
- [ ] We shouldn't publish anything from feature branches

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
