### ISSUE TITLE
Exclude Build and test CI actions on purely document changes.

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#364]
## Description
Exclude Build and test CI actions on purely document changes. Also try exclude gated e2e tests.

## Motivation
It delays merging needlessly and wastes resourced when the change is just documentation.

## Tasks
- [ ] Adjust Github actions/workflows to exclude certain tasks such as building and testing
- [ ] Adjust Github actions/workflows to not require the e2e tests for documentation

## Acceptance criteria
- [ ] No tests are run or compilations are run for documentation changes
- [ ] If documentation is included in code changes, tests and building etc. are run + gate check required

## Risks
- [ ] Required building and testing gets skipped

## Remember to
 - [x] Add `priority` and `team` labels
