### ISSUE TITLE
Decouple Coordinator config tests for Local Stack config

### ISSUE THREAD

**Issue by jpnovais** [Consensys/linea-monorepo#402]
## Description
Coordinator configuration files  inside `/config/coordinator/*.toml` are used in the Unit tests and in to configure the localstack. This coupling causes error when we update the configurations for the local stack even though the functionality was not broken. As configs got bigger and bigger this gets more and more complex when it fails.

We should have 2 separate set of configuration files:
- `coordinator/app/src/test/resources/**.toml` for the unit tests
- `config/coordoniator/**.toml` to configure the local stack (has we have)

To ensure that files inside `config/coordoniator/**.toml` are still valid, we shall have Unit test that loads those files, but does not make assertions on specific values. This will ensure the example we be compatible with the code. 

## Motivation
Improve developer experience and stop waiting time fixing tests

## Tasks
- [ ] Adap the Unit test to read the files from `coordinator/app/src/test/resources`
    - [ ] Create config files for the unit tests
- [ ] Create a test that load the files inside `config/coordoniator/**.toml` to make sure thy are valid

**Comment by Pawar7349** [comment]
Hi @jpnovais,
I would like to work on issue #402. 
Here’s my plan:
Adapt unit tests to use files from   coordinator/app/src/test/resources.
Create configuration files for unit tests.
Add a test to ensure files in  config/coordinator are valid.

**Comment by jpnovais** [comment]
Hi @Pawar7349, yes that seems aligned with the tasks. 
Please, fork the project and open a PR for review. Thanks for the contribution

**Comment by jpnovais** [comment]
Closing as it was done already on #552
