### ISSUE TITLE
Create London EVM Version Opcode Contract

### ISSUE THREAD

**Issue by julien-marchand** [Consensys/linea-monorepo#424]
## Description
Create London EVM Version Opcode Testing Contract.

## Motivation
Being able to test all opcodes are executed with state changes will assist in state reconstruction confidence.

## Tasks
- [ ] Build Full London EVM Opcode Testing Contract with make commands

## Acceptance criteria
- [x] All opcodes are covered including reverts and creates
- [x] Execution of opcode execution is tracked
- [x] Documented for easy understanding
- [x] Extensible for future EVM Versions
- [x] Easily deployable from the Makefile

## Risks
- [x] Missed opcodes

## Remember to
 - [x] Add the `documentation` label in case there is an impact on the documentation
 - [x] Add `priority` and `team` labels
