### ISSUE TITLE
Use Tracer package instead of the uber jar

### ISSUE THREAD

**Issue by fab-10** [Consensys/linea-monorepo#426]
## Description

Part of the process of removing the need for uber jar for plugins, and replace it with plain jar, the Tracer now publishes a new artifact that contains only the jars need by the Tracer plugin and that are not already provided by Besu

## Motivation

Remove the use of uber jar, that can carry duplicated classes, and can cause conflicts at runtime in case different versions of the same classes are present

## Tasks
- [ ] Use the new Tracer archive package when deploying the plugin

## Acceptance criteria
- [ ] There should be no changes in the behavior

## Risks
- [ ] Some classes could not be found, in case the archive still isn't complete

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.

**Comment by fab-10** [comment]
closing in favor of https://github.com/Consensys/linea-besu-package/pull/129
