### ISSUE TITLE
Investigate gas savings for LineaRollup.submitBlobs()

### ISSUE THREAD

**Issue by kyzooghost** [Consensys/linea-monorepo#429]
## Description
Investigate gas saving possibilities in smart contract logic for LineaRollup.submitBlobs()

## Motivation
~5% gas savings on LineaRollup.submitBlobs()

## Tasks
- [x] Write Jira documentation on findings

## Acceptance criteria
- [ ] Jira documentation written and discussed

## Risks
- [ ] State reconstruction may be impaired

## Remember to
 - [x] Add the `documentation` label in case there is an impact on the documentation
 - [x] Add `priority` and `team` labels

**Comment by kyzooghost** [comment]
<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVVrQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--055d6ae07ed86063bed2a446a367612ee3d0d1ca/test-cat.webp" alt="test-cat.webp" />

**Comment by kyzooghost** [comment]
[linea-rollup-gas-saving-investigation.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhvQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8a6b91a00eff964893b66b52e2b1dfde6fd557d/linea-rollup-gas-saving-investigation.pdf)
