### ISSUE TITLE
Standardize smart contract NatSpec comment spelling to US English

### ISSUE THREAD

**Issue by kyzooghost** [Consensys/linea-monorepo#465]
## Description
Standardize smart contract NatSpec comment spelling to US English

## Motivation
docs.linea.build is predominantly US English spelling, so for better consistency with the existing Linea public documentation we want to standardize the spelling in the smart contract NatSpec comments to US English as well

## Tasks
- [ ] Standardize spelling of Linea smart contract NatSpec comments to US English

## Acceptance criteria
- [ ] Linea smart contract NatSpec comments standardized to US English

## Risks
- [ ] May disturb smart contract audit timing, in that we are currently holding back several smart contract PRs on account of the smart contract auditors

## Remember to
 - [x] Add the `documentation` label in case there is an impact on the documentation
 - [x] Add `priority` and `team` labels
 - [x] Add Task for updating the Runbook or adding/updating existing metrics and alerts.

**Comment by kyzooghost** [comment]
Note - consider https://github.com/orsinium-labs/eng

**Comment by kyzooghost** [comment]
Consider - http://app.aspell.net/create

**Comment by kyzooghost** [comment]
Consider - https://github.com/dwyl/english-words
