### ISSUE TITLE
Investigate Upgrading to OpenZeppelin V5 contracts

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#466]
## Description
Investigate Upgrading to OpenZeppelin V5 contracts

## Motivation
Forward / future compatability as well potentially using OpenZeppelin libraries such as the transient reentrancy guard

## Tasks
- [x] Investigate and possibly build a sample POC

## Acceptance criteria
- [ ] Storage layout compatible with existing data
- [ ] Tests all passing
- [ ] Upgrade / switch requires zero downtime

## Risks
- [ ] Storage layout could be broken and it could also
- [ ] Introduce highly complex and unmaintainable code

## Remember to
 - [x] Add the `documentation` label in case there is an impact on the documentation
 - [x] Add `priority` and `team` labels
