### ISSUE TITLE
Improve CI workflows

### ISSUE THREAD

**Issue by bradbown** [Consensys/linea-monorepo#50]
## Description
Take actions to reduce costs of CI workflows.

## Motivation
Reduce costs and unnecessary runs of workflows.

## Tasks
- [ ] Manual triggering for build and e2e test jobs
- [ ] Verify and improve path filters
  - [ ] Check for improvements of monorepo directories
- [ ] Try to reduce machine sizes
- [ ] Switch to arm runners where possible

## Acceptance criteria
- [ ] Duration of workflow runs shouldn't be negatively impacted.

## Risks
- [ ] Correct architecture for runners should be used for creating images.

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
