### ISSUE TITLE
Specify L2MessageService contract abi version

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#56]
## Description
Add contract version constant in the L2MessageService contract.

## Motivation
Contracts versioning consistency.

## Tasks
- [x] Update L2MessageService contract
- [x] Rename previous L2MessageService ABI to match version
- [x] Update gradle to use ABI version
- [x] Rename ABI in postCompile and exported files

## Acceptance criteria
- [x] L2MessageService updated
- [ ] All tests passed
