### ISSUE TITLE
Add Golang caching in CI workflow

### ISSUE THREAD

**Issue by VGau** [Consensys/linea-monorepo#72]
## Description
Add Golang caching in CI workflow

## Motivation
Speed up the pipeline

## Tasks
- [ ] Investigate caching of Golang
- [ ] Apply where applicable

## Acceptance criteria
- [ ] Pipeline runs faster
- [ ] Golang packages downloading does not happen each time
