### ISSUE TITLE
Improve L2NetworkGasPricingService test coverage

### ISSUE THREAD

**Issue by Filter94** [Consensys/linea-monorepo#88]
## Description
`L2NetworkGasPricingService` as it is now, is hard to test. Specifically, `Web3j`, `Web3jBlobExtended` and `VertxHttpJsonRpcClientFactory` input interfaces aren't minimal. They contain more methods than is absolutely needed for `L2NetworkGasPricingService`, which makes them hard to mock / inject test implementations. We can refactor `L2NetworkGasPricingService` to accept interfaces that are more focused on inputs and outputs of this business logic and create tests that would simulate different L1 fees market conditions and verify that L2 pricing is adequate

## Motivation
This is to improve test coverage of the L2 gas pricing logic

## Tasks
- [ ] Refactor `L2NetworkGasPricingService` so it's more easily testable
- [ ] Cover `L2NetworkGasPricingService` with tests:
  - High L1 fees
  - Low L1 fees
  - Normal conditions
  - Normal conditions with a L1 fees spike

## Acceptance criteria
- [ ] `L2NetworkGasPricingService` test coverage is improved and different market conditions are covered

## Risks
- [ ] `L2NetworkGasPricingService` in the tests may be created differently than how it's created in the main Coordinator app. We need to ensure it's created exactly the same way from the E2E tests config file

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
