### ISSUE TITLE
Emit ABI Version event on contract upgrades

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#94]
## Description
Emit ABI Version event on contract upgrades

## Motivation
This will allow external parties and components to know the ABI version to use.

## Tasks
- [x] Emit an event on the LineaRollup on contract upgrades
- [x] Add version for L2MessageService
- [x] Add version for  the TokenBridge

## Acceptance criteria
- [x] Event is emitted on LineaRollup upgrade
