### ISSUE TITLE
Add end to end tests to validate contract upgrade behaviour

### ISSUE THREAD

**Issue by thedarkjester** [Consensys/linea-monorepo#95]
## Description
Add end to end test to validate contract upgrade behaviour.

## Motivation
Increase in confidence that the upgrade pattern works as expected.

## Tasks
- [ ] Update end to end tests that test before and after upgrade for the L2MessageService
- [ ] Update end to end tests that test before and after upgrade for the LineaRollup

## Acceptance criteria
- [ ] Messaging works bidirectionally before and after
- [ ] Blob submission works before and after
- [ ] Finalization works before and after
- [ ] Access Control is set correctly on upgrade

## Risks
- [ ] Missed permissions on upgrade
- [ ] Coordinator integration is required to support V6.0 upgrade
